In [1]:
import pandas, numpy, quandl
import matplotlib.pyplot as plt
from matplotlib import style
import math
from sklearn import preprocessing, cross_validation, svm
from sklearn.linear_model import LinearRegression

D:\Programs\Anaconda\envs\machine-learning\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
style.use('ggplot')

In [30]:
df = quandl.get('WIKI/GOOGL')

In [32]:
df

Open      High       Low    Close      Volume  Ex-Dividend  \
Date                                                                        
2004-08-19  100.010  104.0600   95.9600  100.335  44659000.0          0.0   
2004-08-20  101.010  109.0800  100.5000  108.310  22834300.0          0.0   
2004-08-23  110.760  113.4800  109.0500  109.400  18256100.0          0.0   
2004-08-24  111.240  111.6000  103.5700  104.870  15247300.0          0.0   
2004-08-25  104.760  108.0000  103.8800  106.000   9188600.0          0.0   
2004-08-26  104.950  107.9500  104.6600  107.910   7094800.0          0.0   
2004-08-27  108.100  108.6200  105.6900  106.150   6211700.0          0.0   
2004-08-30  105.280  105.4900  102.0100  102.010   5196700.0          0.0   
2004-08-31  102.320  103.7100  102.1600  102.370   4917800.0          0.0   
2004-09-01  102.700  102.9700   99.6700  100.250   9138200.0          0.0   
2004-09-02   99.090  102.3700   98.9400  101.510  15118600.0          0.0   
2004-09-03  100.950  101.7400   99.3200  100.010   5152400.0          0.0   
2004-09-07  101.010  102.0000   99.6100  101.580   5847500.0          0.0   
2004-09-08  100.740  103.0300  100.5000  102.300   4985600.0          0.0   
2004-09-09  102.500  102.7100  101.0000  102.310   4061700.0          0.0   
2004-09-10  101.470  106.5600  101.3000  105.330   8698800.0          0.0   
2004-09-13  106.630  108.4100  106.4600  107.500   7844100.0          0.0   
2004-09-14  107.440  112.0000  106.7900  111.490  10828900.0          0.0   
2004-09-15  110.560  114.2300  110.2000  112.000  10713000.0          0.0   
2004-09-16  112.340  115.8000  111.6500  113.970   9266300.0          0.0   
2004-09-17  114.420  117.4900  113.5500  117.490   9472500.0          0.0   
2004-09-20  116.950  121.6000  116.7700  119.360  10628700.0          0.0   
2004-09-21  120.200  120.4200  117.5100  117.840   7228700.0          0.0   
2004-09-22  117.450  119.6700  116.8100  118.380   7581200.0          0.0   
2004-09-23  118.840  122.6300  117.0200  120.820   8535600.0          0.0   
2004-09-24  120.970  124.1000  119.7600  119.830   9123400.0          0.0   
2004-09-27  119.560  120.8800  117.8000  118.260   7066100.0          0.0   
2004-09-28  121.150  127.4000  120.2100  126.860  16929000.0          0.0   
2004-09-29  126.530  135.0200  126.2300  131.080  30516400.0          0.0   
2004-09-30  129.899  132.3000  129.0000  129.600  13758000.0          0.0   
...             ...       ...       ...      ...         ...          ...   
2017-03-07  847.260  853.3300  845.5200  851.150   1018514.0          0.0   
2017-03-08  853.120  856.9300  851.2500  853.640   1019962.0          0.0   
2017-03-09  853.690  860.7100  852.6700  857.840   1322603.0          0.0   
2017-03-10  862.700  864.2290  857.6100  861.405   1326432.0          0.0   
2017-03-13  860.830  867.1300  860.8200  864.580   1151647.0          0.0   
2017-03-14  863.750  867.5800  860.1300  865.910   1034143.0          0.0   
2017-03-15  867.940  869.8800  861.2950  868.390   1298959.0          0.0   
2017-03-16  870.530  872.7100  867.5200  870.000   1086243.0          0.0   
2017-03-17  873.680  874.4200  868.3700  872.370   1832275.0          0.0   
2017-03-20  869.480  870.3400  864.6650  867.870   1491235.0          0.0   
2017-03-21  870.060  873.4700  847.6870  850.140   2506510.0          0.0   
2017-03-22  849.480  855.3500  847.0000  849.800   1345140.0          0.0   
2017-03-23  841.390  841.6900  833.0000  839.650   3267477.0          0.0   
2017-03-24  842.000  844.0000  829.1000  835.140   2080936.0          0.0   
2017-03-27  828.090  841.3800  824.3000  838.510   1922073.0          0.0   
2017-03-28  839.690  845.4000  832.2650  840.630   1508672.0          0.0   
2017-03-29  842.750  851.5850  841.3800  849.870   1431998.0          0.0   
2017-03-30  851.980  852.0000  846.7700  849.480    944421.0          0.0   
2017-03-31  846.830  849.5600  845.2445  847.800   1375570.0          0.0   
2017-04-03 

In [37]:
?? pandas.core.frame.DataFrame.iloc

In [18]:
df = df[['Adj. Open',  'Adj. High',  'Adj. Low',  'Adj. Close', 'Adj. Volume']]
df['HL_PCT'] = (df['Adj. High'] - df['Adj. Low']) / df['Adj. Close'] * 100.0
df['PCT_change'] = ( df['Adj. Close'] - df['Adj. Open'])/df['Adj. Open'] *100.0

In [19]:
df = df[['Adj. Close','HL_PCT','PCT_change', 'Adj. Volume']]

In [20]:
df.fillna(value=-99999, inplace=True)

In [21]:
shift_label = int(math.ceil(0.01*len(df)))

In [22]:
df['label'] = df['Adj. Close']
X = numpy.array(df.drop(['label'], 1))
y = numpy.array(df['label'])

In [23]:
X = preprocessing.scale(X)
X_lately = X[-shift_label:]
X = X[:-shift_label]
y = y[shift_label:] 

In [24]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.2)

In [25]:
clf = LinearRegression(n_jobs=-1)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.97192393474067784

In [26]:
X_lately

array([[ 2.36574625, -1.02028651,  0.02799078, -0.86834593],
       [ 2.3569119 , -0.8812092 ,  0.04886844, -0.86465077],
       [ 2.37584961, -0.88084252,  0.31747493, -0.86609294],
       [ 2.38800294, -1.05900301,  0.05706869, -0.86591996],
       [ 2.40850252, -0.86695708,  0.33513155, -0.82976502],
       [ 2.42590277, -0.98623307, -0.08096655, -0.82930759],
       [ 2.44139947, -1.01347443,  0.30210527, -0.85018824],
       [ 2.44789101, -0.92126164,  0.18075303, -0.86422583],
       [ 2.45999553, -0.83066507,  0.05111346, -0.83258964],
       [ 2.4678537 , -1.10762993, -0.0226116 , -0.85800171],
       [ 2.47942132, -1.03913294, -0.0808556 , -0.76887716],
       [ 2.45745748, -1.0671172 , -0.10389452, -0.80961943],
       [ 2.37091995,  0.61341975, -1.480127  , -0.68832982],
       [ 2.36926046, -0.83492273,  0.04184183, -0.82707264],
       [ 2.3197198 , -0.79792604, -0.11804219, -0.59742106],
       [ 2.29770715, -0.26868047, -0.51562627, -0.73917093],
       [ 2.31415563, -0.

In [27]:
forecast = clf.predict(X_lately)

In [28]:
forecast

array([ 858.8336444 ,  856.79062945,  860.70266677,  863.43415387,
        867.2364064 ,  870.90833559,  874.24079144,  875.42448803,
        877.62627439,  879.75510038,  881.73785484,  877.41796419,
        856.34152075,  859.12305723,  848.29457086,  843.23264652,
        846.58135908,  849.2601638 ,  858.99825299,  859.33836282,
        857.69996696,  865.5114264 ,  862.34389225,  857.32229249,
        854.14948911,  851.454782  ,  851.51484687,  849.09827636,
        851.24382933,  849.96994851,  863.85463246,  863.75822645])

In [34]:
X

array([[-1.53287037,  4.17397094,  0.2297345 ,  4.3474084 ],
       [-1.51334771,  4.06712293,  4.74367251,  1.74012528],
       [-1.5106794 ,  1.33155825, -0.78582874,  1.19319159],
       ..., 
       [ 2.3454907 , -0.91137031, -0.16957457, -0.82253549],
       [ 2.40318239, -0.78860672,  0.42971033, -0.77050236],
       [ 2.3695045 , -0.88317595, -0.47617228, -0.83924837]])